[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build --no-cache -t app ."

[deploy]
startCommand = "gunicorn --workers 4 --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile - app:create_app()"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
FLASK_APP = "app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
PORT = "8000" 