services:
  - type: web
    name: task-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT --timeout 120 app:create_app()
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString

databases:
  - name: taskmanager-db
    databaseName: taskmanager
    user: taskmanager
    plan: free 